//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceSphere
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int service_id { get; set; }
        public int provider_id { get; set; }
        public Nullable<System.DateTime> booking_date { get; set; }
        public System.DateTime service_date { get; set; }
        public string service_time { get; set; }
        public string address { get; set; }
        public string description { get; set; }
        public string status { get; set; }
    }
}
