//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceSphere
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookingtab
    {
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int provider_id { get; set; }
        public int service_id { get; set; }
        public System.DateTime booking_date { get; set; }
        public string booking_status { get; set; }
    }
}
