//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceSphere
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class servicesphereEntities : DbContext
    {
        public servicesphereEntities()
            : base("name=servicesphereEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admintab> admintabs { get; set; }
        public virtual DbSet<categorytab> categorytabs { get; set; }
        public virtual DbSet<logintab> logintabs { get; set; }
        public virtual DbSet<providertab> providertabs { get; set; }
        public virtual DbSet<servicetab> servicetabs { get; set; }
        public virtual DbSet<usertab> usertabs { get; set; }
    
        public virtual int sp_adminregister(Nullable<int> adminid, string adminname, string adminemail, Nullable<long> phone)
        {
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(int));
    
            var adminnameParameter = adminname != null ?
                new ObjectParameter("adminname", adminname) :
                new ObjectParameter("adminname", typeof(string));
    
            var adminemailParameter = adminemail != null ?
                new ObjectParameter("adminemail", adminemail) :
                new ObjectParameter("adminemail", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_adminregister", adminidParameter, adminnameParameter, adminemailParameter, phoneParameter);
        }
    
        public virtual int sp_approve_provider(Nullable<int> provider_id)
        {
            var provider_idParameter = provider_id.HasValue ?
                new ObjectParameter("provider_id", provider_id) :
                new ObjectParameter("provider_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_approve_provider", provider_idParameter);
        }
    
        public virtual int sp_block_provider(Nullable<int> provider_id)
        {
            var provider_idParameter = provider_id.HasValue ?
                new ObjectParameter("provider_id", provider_id) :
                new ObjectParameter("provider_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_block_provider", provider_idParameter);
        }
    
        public virtual int sp_category_delete(Nullable<int> cat_id)
        {
            var cat_idParameter = cat_id.HasValue ?
                new ObjectParameter("cat_id", cat_id) :
                new ObjectParameter("cat_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_category_delete", cat_idParameter);
        }
    
        public virtual int sp_category_insert(string catname)
        {
            var catnameParameter = catname != null ?
                new ObjectParameter("catname", catname) :
                new ObjectParameter("catname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_category_insert", catnameParameter);
        }
    
        public virtual ObjectResult<sp_category_select_Result> sp_category_select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_category_select_Result>("sp_category_select");
        }
    
        public virtual int sp_delete_service(Nullable<int> service_id)
        {
            var service_idParameter = service_id.HasValue ?
                new ObjectParameter("service_id", service_id) :
                new ObjectParameter("service_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_service", service_idParameter);
        }
    
        public virtual ObjectResult<sp_get_approved_providers_Result> sp_get_approved_providers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_approved_providers_Result>("sp_get_approved_providers");
        }
    
        public virtual ObjectResult<sp_get_blocked_providers_Result> sp_get_blocked_providers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_blocked_providers_Result>("sp_get_blocked_providers");
        }
    
        public virtual ObjectResult<sp_get_pending_providers_Result> sp_get_pending_providers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_pending_providers_Result>("sp_get_pending_providers");
        }
    
        public virtual ObjectResult<sp_get_service_by_id_Result> sp_get_service_by_id(Nullable<int> service_id)
        {
            var service_idParameter = service_id.HasValue ?
                new ObjectParameter("service_id", service_id) :
                new ObjectParameter("service_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_service_by_id_Result>("sp_get_service_by_id", service_idParameter);
        }
    
        public virtual int sp_insert_service(Nullable<int> provider_regid, Nullable<int> category_id, string service_name, string service_description, Nullable<int> service_price, string service_image, string service_status, string location)
        {
            var provider_regidParameter = provider_regid.HasValue ?
                new ObjectParameter("provider_regid", provider_regid) :
                new ObjectParameter("provider_regid", typeof(int));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            var service_nameParameter = service_name != null ?
                new ObjectParameter("service_name", service_name) :
                new ObjectParameter("service_name", typeof(string));
    
            var service_descriptionParameter = service_description != null ?
                new ObjectParameter("service_description", service_description) :
                new ObjectParameter("service_description", typeof(string));
    
            var service_priceParameter = service_price.HasValue ?
                new ObjectParameter("service_price", service_price) :
                new ObjectParameter("service_price", typeof(int));
    
            var service_imageParameter = service_image != null ?
                new ObjectParameter("service_image", service_image) :
                new ObjectParameter("service_image", typeof(string));
    
            var service_statusParameter = service_status != null ?
                new ObjectParameter("service_status", service_status) :
                new ObjectParameter("service_status", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_service", provider_regidParameter, category_idParameter, service_nameParameter, service_descriptionParameter, service_priceParameter, service_imageParameter, service_statusParameter, locationParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logid", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logincountid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logincountid", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_logininsert(Nullable<int> regid, string username, string password, string usertype)
        {
            var regidParameter = regid.HasValue ?
                new ObjectParameter("regid", regid) :
                new ObjectParameter("regid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var usertypeParameter = usertype != null ?
                new ObjectParameter("usertype", usertype) :
                new ObjectParameter("usertype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", regidParameter, usernameParameter, passwordParameter, usertypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxidlogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxidlogin");
        }
    
        public virtual int sp_providersregister(Nullable<int> providerregid, string bussinessname, string address, string email, Nullable<long> phone, string isapproved)
        {
            var providerregidParameter = providerregid.HasValue ?
                new ObjectParameter("providerregid", providerregid) :
                new ObjectParameter("providerregid", typeof(int));
    
            var bussinessnameParameter = bussinessname != null ?
                new ObjectParameter("bussinessname", bussinessname) :
                new ObjectParameter("bussinessname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(long));
    
            var isapprovedParameter = isapproved != null ?
                new ObjectParameter("isapproved", isapproved) :
                new ObjectParameter("isapproved", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_providersregister", providerregidParameter, bussinessnameParameter, addressParameter, emailParameter, phoneParameter, isapprovedParameter);
        }
    
        public virtual int sp_unblock_provider(Nullable<int> provider_id)
        {
            var provider_idParameter = provider_id.HasValue ?
                new ObjectParameter("provider_id", provider_id) :
                new ObjectParameter("provider_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_unblock_provider", provider_idParameter);
        }
    
        public virtual int sp_update_service(Nullable<int> service_id, Nullable<int> category_id, string service_name, string service_description, Nullable<int> service_price, string service_image, string service_status, string location)
        {
            var service_idParameter = service_id.HasValue ?
                new ObjectParameter("service_id", service_id) :
                new ObjectParameter("service_id", typeof(int));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            var service_nameParameter = service_name != null ?
                new ObjectParameter("service_name", service_name) :
                new ObjectParameter("service_name", typeof(string));
    
            var service_descriptionParameter = service_description != null ?
                new ObjectParameter("service_description", service_description) :
                new ObjectParameter("service_description", typeof(string));
    
            var service_priceParameter = service_price.HasValue ?
                new ObjectParameter("service_price", service_price) :
                new ObjectParameter("service_price", typeof(int));
    
            var service_imageParameter = service_image != null ?
                new ObjectParameter("service_image", service_image) :
                new ObjectParameter("service_image", typeof(string));
    
            var service_statusParameter = service_status != null ?
                new ObjectParameter("service_status", service_status) :
                new ObjectParameter("service_status", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_service", service_idParameter, category_idParameter, service_nameParameter, service_descriptionParameter, service_priceParameter, service_imageParameter, service_statusParameter, locationParameter);
        }
    
        public virtual int sp_userregister(Nullable<int> userid, string username, string photo, string address, string email, string status)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userregister", useridParameter, usernameParameter, photoParameter, addressParameter, emailParameter, statusParameter);
        }
    
        public virtual ObjectResult<sp_view_provider_services_Result> sp_view_provider_services(Nullable<int> provider_id)
        {
            var provider_idParameter = provider_id.HasValue ?
                new ObjectParameter("provider_id", provider_id) :
                new ObjectParameter("provider_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_view_provider_services_Result>("sp_view_provider_services", provider_idParameter);
        }
    
        public virtual ObjectResult<string> sp_check_provider_status(Nullable<int> provider_id)
        {
            var provider_idParameter = provider_id.HasValue ?
                new ObjectParameter("provider_id", provider_id) :
                new ObjectParameter("provider_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_check_provider_status", provider_idParameter);
        }
    }
}
