//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceSphere
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class servicesphereEntities : DbContext
    {
        public servicesphereEntities()
            : base("name=servicesphereEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admintab> admintabs { get; set; }
        public virtual DbSet<logintab> logintabs { get; set; }
        public virtual DbSet<providertab> providertabs { get; set; }
        public virtual DbSet<usertab> usertabs { get; set; }
    
        public virtual int sp_adminregister(Nullable<int> adminid, string adminname, string adminemail, Nullable<long> phone)
        {
            var adminidParameter = adminid.HasValue ?
                new ObjectParameter("adminid", adminid) :
                new ObjectParameter("adminid", typeof(int));
    
            var adminnameParameter = adminname != null ?
                new ObjectParameter("adminname", adminname) :
                new ObjectParameter("adminname", typeof(string));
    
            var adminemailParameter = adminemail != null ?
                new ObjectParameter("adminemail", adminemail) :
                new ObjectParameter("adminemail", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_adminregister", adminidParameter, adminnameParameter, adminemailParameter, phoneParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logid", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_logincountid(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_logincountid", usernameParameter, passwordParameter);
        }
    
        public virtual int sp_logininsert(Nullable<int> regid, string username, string password, string usertype)
        {
            var regidParameter = regid.HasValue ?
                new ObjectParameter("regid", regid) :
                new ObjectParameter("regid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var usertypeParameter = usertype != null ?
                new ObjectParameter("usertype", usertype) :
                new ObjectParameter("usertype", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_logininsert", regidParameter, usernameParameter, passwordParameter, usertypeParameter);
        }
    
        public virtual ObjectResult<string> sp_logintype(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_logintype", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_maxidlogin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_maxidlogin");
        }
    
        public virtual int sp_providersregister(Nullable<int> providerregid, string bussinessname, string address, string email, Nullable<long> phone, string isapproved)
        {
            var providerregidParameter = providerregid.HasValue ?
                new ObjectParameter("providerregid", providerregid) :
                new ObjectParameter("providerregid", typeof(int));
    
            var bussinessnameParameter = bussinessname != null ?
                new ObjectParameter("bussinessname", bussinessname) :
                new ObjectParameter("bussinessname", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone.HasValue ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(long));
    
            var isapprovedParameter = isapproved != null ?
                new ObjectParameter("isapproved", isapproved) :
                new ObjectParameter("isapproved", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_providersregister", providerregidParameter, bussinessnameParameter, addressParameter, emailParameter, phoneParameter, isapprovedParameter);
        }
    
        public virtual int sp_userregister(Nullable<int> userid, string username, string photo, string address, string email, string status)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var photoParameter = photo != null ?
                new ObjectParameter("photo", photo) :
                new ObjectParameter("photo", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_userregister", useridParameter, usernameParameter, photoParameter, addressParameter, emailParameter, statusParameter);
        }
    }
}
