//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceSphere
{
    using System;
    using System.Collections.Generic;
    
    public partial class providertab
    {
        public int provider_id { get; set; }
        public Nullable<int> reg_id { get; set; }
        public string bussiness_name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public long phone { get; set; }
        public string is_approved { get; set; }
    }
}
