//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace serviceSphere
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviewtab
    {
        public int review_id { get; set; }
        public int booking_id { get; set; }
        public int user_id { get; set; }
        public int provider_id { get; set; }
        public int service_id { get; set; }
        public int rating { get; set; }
        public string review_msg { get; set; }
    }
}
